# A snapshot resolver dictates the compiler version and the set of packages to
# be used for project dependencies.
resolver: lts-12.9

# User packages to be built.
packages:
- './backend'
- './common'
- './telescope'

# Dependency packages to be pulled from upstream that are not in the resolver
# using the same syntax as the packages field.
extra-deps:
  - monoidal-containers-0.4.0.0
  - reactive-banana-1.2.0.0
  - ref-tf-0.4.0.1
  - servant-options-0.1.0.0
  - github: reflex-frp/reflex
    commit: 2c089a255184ac1ae8250be44dcb44fddad7ddd5

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.7"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
