name:                progress-dom
version:             0.1.0.0
github:              "barischrooneyj/progress-dom"
license:             BSD3
author:              "Jeremy Barisch-Rooney"
maintainer:          "barischrooneyj@gmail.com"
copyright:           "Jeremy Barisch-Rooney (c) 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/barischrooneyj/progress-dom#readme>

dependencies:
- base >= 4.7 && < 5
- reflex-dom

library:
  source-dirs: src

executables:
  progress-dom-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - progress-dom

tests:
  progress-dom-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - progress-dom
