name:                common
version:             0.1.0.0
github:              "barischrooneyj/progress/common"
license:             BSD3
author:              "Jeremy Barisch Rooney"
maintainer:          "barischrooneyj@gmail.com"
copyright:           "2018 Jeremy Barisch Rooney"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/common#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  common-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - common
